version: '3.8'
services:
  db:
    platform: linux/x86_64
    image: postgres:14.1-alpine
    restart: on-failure
    container_name: 'linkz-db'
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - 5432:5432
    volumes:
      - ./tmp/postgres-data:/var/lib/postgresql/data/
    networks: [ 'linkz' ]

  db-is-ready: &db-is-ready
    image: wait-for-it
    build:
      context: ./misc/docker/wait-for-it/
    command: [ "/wait-for-it.sh", "db:5432", "--", "echo", "alive"]
    depends_on:
      - db
    networks: [ "linkz" ]

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: 'linkz-app'
    depends_on:
      - db-is-ready
    ports:
      - 3000:3000
    environment:
      - DB_HOST=db
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE=${DB_DATABASE}
    networks: [ 'linkz' ]

volumes:
  db:
    driver: local
networks:
  linkz:
    driver: bridge